"""create main tables

Revision ID: b6ad186f5e95
Revises:
Create Date: 2023-01-29 18:40:51.676138

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b6ad186f5e95"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("goal", mysql.DECIMAL(), nullable=False),
        sa.Column("start", mysql.DECIMAL(), nullable=False),
        sa.Column("weeks_remaining", sa.Integer(), nullable=False),
        sa.Column("reached", mysql.DECIMAL(), nullable=False),
        sa.Column("starts_at", sa.DATE(), nullable=False),
        sa.Column("ends_at", sa.DATE(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weeks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("deposit", mysql.DECIMAL(), nullable=False),
        sa.Column("balance", mysql.DECIMAL(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weeks")
    op.drop_table("goals")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
